"""create access requests table

Revision ID: c6bc3b3821fa
Revises: 6053f18e9a24
Create Date: 2026-07-20 22:55:46.193189

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c6bc3b3821fa"
down_revision = "6053f18e9a24"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("requester_id", sa.Integer(), nullable=False),
        sa.Column("data_product_id", sa.Integer(), nullable=False),
        sa.Column("access_level", sa.String(length=50), nullable=False),
        sa.Column("business_justification", sa.Text(), nullable=False),
        sa.Column("expiration_date", sa.Date(), nullable=False),
        sa.Column(
            "status", sa.String(length=50), server_default="DRAFT", nullable=False
        ),
        sa.Column(
            "source_system",
            sa.String(length=50),
            server_default="INTERNAL",
            nullable=False,
        ),
        sa.Column("servicenow_request_number", sa.String(length=100), nullable=True),
        sa.Column("servicenow_sys_id", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["data_product_id"],
            ["data_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("access_requests")
    # ### end Alembic commands ###
